---
language: node_js
node_js:
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - "12"

dist: xenial

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

branches:
  only:
    - master
    # npm version tags
    - /^v\d+\.\d+\.\d+/

jobs:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

  include:
    # runs linting and tests with current locked deps
    - stage: "Tests"
      name: "Tests"
      script:
<<<<<<< HEAD
        - npm run lint:hbs
        - npm run lint:js
        - npm test
=======
        - yarn lint
        - yarn test:ember

    - stage: "Additional Tests"
      name: "Floating Dependencies"
      install:
        - yarn install --no-lockfile --non-interactive
      script:
        - yarn test:ember
>>>>>>> 280e081 (v3.5.0...v3.28.5)

    # we recommend new addons test the current and previous LTS
    # as well as latest stable release (bonus points to beta/canary)
    - env: EMBER_TRY_SCENARIO=ember-lts-3.24
    - env: EMBER_TRY_SCENARIO=ember-lts-3.28
    - env: EMBER_TRY_SCENARIO=ember-release
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary
    - env: EMBER_TRY_SCENARIO=ember-default-with-jquery
    - env: EMBER_TRY_SCENARIO=ember-classic
    - env: EMBER_TRY_SCENARIO=embroider-safe
    - env: EMBER_TRY_SCENARIO=embroider-optimized

before_install:
<<<<<<< HEAD
  - npm config set spin false
  - npm install -g npm@4
  - npm --version
=======
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
>>>>>>> 280e081 (v3.5.0...v3.28.5)

script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO
